### ISSUE TITLE
Consider supporting UStealth for the vWii

### ISSUE THREAD

**Issue by Mystro256** [devkitPro/libfat#8]
For Wii homebrew on a Wii U (vWii) UStealth usually used, so when using a FAT usb drive, it won't complain about an unformatted drive when booting the system. This just involves changing the 0xAA flag to 0xAB, so the Wii U doesn't recognise it as a valid drive.

To do this, most Wii homebrew recompiles their code with a modified libfat (called libfatmod).
I uploaded the source to github (for ease of updating it and availability), but if you're not opposed to cherry picking the commit that implements this feature, I can remove my fork.

The commit in question can be found here:
https://github.com/Mystro256/libfatmod/commit/829e28632b5cbc5bfd982f0110ed5e4f82b9515b

Feel free to reject this if you don't want to include it, or wrap it in a "**#if SOME_WII_FLAG ... #endif**" if you don't want this to affect nds, gc or gba.

**Comment by WinterMute** [comment]
Sorry, only just noticed this when digging through github notifications.

What exactly does this do and why?

**Comment by Mystro256** [comment]
Oh yes, I forgot about this.

On the Wii U if you plug in a USB, it always asks to reformat it on the Wii U screen. By changing BPB_bootSig_AA to something other than AA, it no longer recognizes the drive. The "UStealth" tools just changes the AA to AB (and back), and a bunch of homebrew have compiled against modified versions of libfat to accommodate this (dubbed "libfatmod"). I just uploaded the source onto github for convenience.

See the commit listed above. Also here's the original thread from what I can see: https://gbatemp.net/threads/ustealth-wii-u-format-disk-nag-workaround.352786/

**Comment by WinterMute** [comment]
This is completely inappropriate, sorry

**Comment by Mystro256** [comment]
Fair enough, it's an ugly workaround to say the least. Thanks
